### ISSUE TITLE
Tags should not be started by 'v'

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataDashboardBundle#2]
If we want to keep sonata organisation: https://github.com/Soullivaneuh/SonataAdminBundle/releases

cc @rande

**Comment by Soullivaneuh** [comment]
ping @qsomazzi

**Comment by qsomazzi** [comment]
fixed

**Comment by Soullivaneuh** [comment]
This should be deleted: https://github.com/sonata-project/SonataDashboardBundle/releases/tag/v0.0.1

**Comment by Soullivaneuh** [comment]
Deleted by @rande.

**Comment by Soullivaneuh** [comment]
@qsomazzi Tag is back.

Bad manipulation?

**Comment by qsomazzi** [comment]
Yes, will check that soon

**Comment by qsomazzi** [comment]
done
