### ISSUE TITLE
Lack of info

### ISSUE THREAD

**Issue by plouc** [sonata-project/SonataDashboardBundle#3]
We should include a sample dashboard screenshot on the readme, and the doc referenced in the readme does not seem to exist.

**Comment by core23** [comment]
@qsomazzi Can you give me a short introduction how to use this bundle? It looks awesome, but I have no idea how to include the created dashboards :/

**Comment by OskarStark** [comment]
:+1: @plouc

**Comment by qsomazzi** [comment]
@core23 Sure, for the moment this bundle is in WIP, you can manage Dashboard and Widgets but there isn't anything to handle the display for the moment. You have to do it from yourself for the moment. I planned to work on this bundle when i got some free time to make it the default Sonata Dashboard page (and replace or add possibility to override the one with yml configuration).

**Comment by rande** [comment]
@core23 the bundle is based on page bundle, but dedicated to dashboard.

**Comment by OskarStark** [comment]
:+1: @qsomazzi is there a ui already?

**Comment by qsomazzi** [comment]
@OskarStark no, not a clean one at least, I've done some tests for the moment, but not concluded

**Comment by OskarStark** [comment]
ok keep us updated please

**Comment by stphnpt** [comment]
@qsomazzi Can you share the "not clean" ui you already have through a dedicated "dev" branch of this bundle for example ?
