### ISSUE TITLE
Status of this bundle

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataDashboardBundle#30]
What is the status of this bundle? Is it stable? What is missing?

This question is for the new version management.

**Comment by core23** [comment]
Refs https://github.com/sonata-project/SonataDashboardBundle/issues/3

Ping @qsomazzi

**Comment by qsomazzi** [comment]
Hello @Soullivaneuh and @core23,

The status of this bundle is in WIP but i don't have any time to work on this. It's working on production, and seems stable (no bug reported on this) but the whole display UI is missing (you can build a dashboard, but you have to do everything to display it as your wish).

At the origin i've started this to offer a new dashboard builder (like page and blocks) to answer to a project need. 

Feel free to improve it as your wish :)

**Comment by Soullivaneuh** [comment]
0.x mean BC break allowed even if stable. :+1: for me.

**Comment by Soullivaneuh** [comment]
But the branch alias must be set to 0.x and the branch should be changed to before it IMHO.

@qsomazzi If you agree with the logic proposed by @core23, I can handle it.

**Comment by qsomazzi** [comment]
I agree :)

**Comment by OskarStark** [comment]
> @qsomazzi If you agree with the logic proposed by @core23, I can handle it.

Thank you @Soullivaneuh 👍

**Comment by Soullivaneuh** [comment]
Ok @qsomazzi I'll look at it soon. :+1:

**Comment by Soullivaneuh** [comment]
@qsomazzi I pushed the 0.x branch and set it as the main branch. I have to close remaining PRs.

Dev-kit is coming soon.

**Comment by core23** [comment]
Not sure if we need a `0.x` branch. A zero branch means, that BC breaks are allowed.

**Comment by Soullivaneuh** [comment]
> Not sure if we need a 0.x branch. A zero branch means, that BC breaks are allowed.

@core23 Yes and this is what you want as this bundle is still WIP.
