### ISSUE TITLE
Possible simplification

### ISSUE THREAD

**Issue by stphnpt** [sonata-project/SonataDashboardBundle#33]
Why defining a BlockInteractor class ? It seems to me that all methods are to interact either with Block or Dashboard and persistence layer so that all methods could (should ?) be moved to BlockManager or DashboardManager.

For example:

- getBlock($id) is just BlockManager->find($id), no ?
- getBlocksById((DashboardInterface $dashboard) is just $dashboard->getBlocks() ordered by block position and can be moved to DashboardManager Class
- saveBlocksPosition ... can be moved to BlockManager Class
- createNewContainer ... can be moved to BlockManager Class
BTW, $container->setCreatedAt(new \DateTime()) and setUpdatedAt(new \DateTime()) are not necessary because already done on prepersist in BaseBlock and executed when blockManager->save($container);
- loadDashboardBlocks(DashboardInterface $dashboard) can be moved to DashboardManager Class
- getEntityManager() is just BlockManager->getEntityManager(), no ? So that there is no need to pass registry in the construct

In my eyes, having only Dashboard and Block and their respective managers would simplify the bundle.

**Comment by greg0ire** [comment]
I don't know this bundle, but simplification is good, and the name of this class is not very meaningful, so I would say go ahead and make a PR to demonstrate the benefits.

**Comment by stphnpt** [comment]
In fact, I see it is a WIP, mainly duplicating class/logic already existing in SonataPageBundle ("page" and "block" entities being here "dashboard" and "block" entities): I may not have captured the intent behind this bundle and the "big picture" ... I'm going to dig deeper ! Feel free to provide more info if you have some.

**Comment by greg0ire** [comment]
> Feel free to provide more info if you have some.

I don't know this bundle at all :P

> I'm going to dig deeper ! 

Maybe have a look at the git history? If you don't get a clear intent from here, maybe ask the author of the class then?
