### ISSUE TITLE
Documentation on the website

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataDashboardBundle#49]
The documentation is currently not present on the website: https://sonata-project.org/bundles/dashboard

**Comment by OskarStark** [comment]
Maybe @rande can help?

**Comment by Soullivaneuh** [comment]
I could too. Just added this issue as a remember. :+1:

**Comment by OskarStark** [comment]
> I could too. Just added this issue as a remember. 👍

Didn't know that 😄

**Comment by Soullivaneuh** [comment]
@sonata-project/contributors On which section should I put this one? Admin ? Feature ?

https://sonata-project.org/bundles/

**Comment by greg0ire** [comment]
Admin (it has a dependency on the admin bundle).

**Comment by Soullivaneuh** [comment]
Added to the doc builder and the website: https://sonata-project.org/bundles/dashboard/master/doc/index.html

No doc for the moment. I think we have to wait the doc task to be running...

cc @rande

**Comment by Soullivaneuh** [comment]
The doc appeared, victory! :tada:
