### ISSUE TITLE
Create Core widgets

### ISSUE THREAD

**Issue by qsomazzi** [sonata-project/SonataDashboardBundle#7]
Would be nice to have to defaults widgets like 'count users' or that stuff based on adminLTE 2 design 
![capture d ecran 2015-08-06 a 10 39 12](https://cloud.githubusercontent.com/assets/1943676/9107422/6dd8745a-3c27-11e5-89e9-07d4a33f769f.png)
![capture d ecran 2015-08-06 a 10 39 23](https://cloud.githubusercontent.com/assets/1943676/9107423/6ddcbe02-3c27-11e5-9dc4-e9d4bd093a76.png)

**Comment by Soullivaneuh** [comment]
:+1:

**Comment by OskarStark** [comment]
:+1:
